# Generated by Django 4.2.10 on 2024-02-11 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentName',
            fields=[
                ('name_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=13)),
                ('pollingunit_uniqueid', models.IntegerField()),
            ],
            options={
                'db_table': 'agentname',
            },
        ),
        migrations.CreateModel(
            name='AnnouncedLgaResults',
            fields=[
                ('result_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('lga_name', models.CharField(max_length=50)),
                ('party_abbreviation', models.CharField(max_length=4)),
                ('party_score', models.IntegerField()),
                ('entered_by_user', models.CharField(max_length=50)),
                ('date_entered', models.DateTimeField()),
                ('user_ip_address', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'announced_lga_results',
            },
        ),
        migrations.CreateModel(
            name='AnnouncedPuResults',
            fields=[
                ('result_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('polling_unit_uniqueid', models.CharField(max_length=50)),
                ('party_abbreviation', models.CharField(max_length=4)),
                ('party_score', models.IntegerField()),
                ('entered_by_user', models.CharField(max_length=50)),
                ('date_entered', models.DateTimeField()),
                ('user_ip_address', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'announced_pu_results',
            },
        ),
        migrations.CreateModel(
            name='AnnouncedStateResults',
            fields=[
                ('result_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=50)),
                ('party_abbreviation', models.CharField(max_length=4)),
                ('party_score', models.IntegerField()),
                ('entered_by_user', models.CharField(max_length=50)),
                ('date_entered', models.DateTimeField()),
                ('user_ip_address', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'announced_state_results',
            },
        ),
        migrations.CreateModel(
            name='AnnouncedWardResults',
            fields=[
                ('result_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('ward_name', models.CharField(max_length=50)),
                ('party_abbreviation', models.CharField(max_length=4)),
                ('party_score', models.IntegerField()),
                ('entered_by_user', models.CharField(max_length=50)),
                ('date_entered', models.DateTimeField()),
                ('user_ip_address', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'announced_ward_results',
            },
        ),
        migrations.CreateModel(
            name='LGA',
            fields=[
                ('uniqueid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('lga_id', models.IntegerField()),
                ('lga_name', models.CharField(max_length=50)),
                ('state_id', models.IntegerField()),
                ('lga_description', models.TextField(null=True)),
                ('entered_by_user', models.CharField(max_length=50)),
                ('date_entered', models.DateTimeField()),
                ('user_ip_address', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'lga',
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('partyid', models.CharField(max_length=11)),
                ('partyname', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'party',
            },
        ),
        migrations.CreateModel(
            name='PollingUnit',
            fields=[
                ('uniqueid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('polling_unit_id', models.IntegerField()),
                ('ward_id', models.IntegerField()),
                ('lga_id', models.IntegerField()),
                ('uniquewardid', models.IntegerField(null=True)),
                ('polling_unit_number', models.CharField(max_length=50, null=True)),
                ('polling_unit_name', models.CharField(max_length=50, null=True)),
                ('polling_unit_description', models.TextField(null=True)),
                ('lat', models.CharField(max_length=255, null=True)),
                ('long', models.CharField(max_length=255, null=True)),
                ('entered_by_user', models.CharField(max_length=50)),
                ('date_entered', models.DateTimeField()),
                ('user_ip_address', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'polling_unit',
            },
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('state_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'states',
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('uniqueid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('ward_id', models.IntegerField()),
                ('ward_name', models.CharField(max_length=50)),
                ('lga_id', models.IntegerField()),
                ('ward_description', models.TextField(null=True)),
                ('entered_by_user', models.CharField(max_length=50)),
                ('date_entered', models.DateTimeField()),
                ('user_ip_address', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ward',
            },
        ),
    ]
