# Generated by Django 4.2.10 on 2024-02-12 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncedStateResults',
            fields=[
                ('result_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=50)),
                ('party_abbreviation', models.CharField(max_length=4)),
                ('party_score', models.IntegerField()),
                ('entered_by_user', models.CharField(max_length=50)),
                ('date_entered', models.DateTimeField()),
                ('user_ip_address', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'announced_state_results',
            },
        ),
        migrations.CreateModel(
            name='LGA',
            fields=[
                ('uniqueid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('lga_id', models.IntegerField(unique=True)),
                ('lga_name', models.CharField(max_length=50, unique=True)),
                ('lga_description', models.TextField(null=True)),
                ('entered_by_user', models.CharField(max_length=50)),
                ('date_entered', models.DateTimeField()),
                ('user_ip_address', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'lga',
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('partyid', models.CharField(max_length=11)),
                ('partyname', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'party',
            },
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('state_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'states',
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('uniqueid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('ward_id', models.IntegerField()),
                ('ward_name', models.CharField(max_length=50, unique=True)),
                ('ward_description', models.TextField(null=True)),
                ('entered_by_user', models.CharField(max_length=50)),
                ('date_entered', models.DateTimeField()),
                ('user_ip_address', models.CharField(max_length=50)),
                ('lga_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='election.lga', to_field='lga_id')),
            ],
            options={
                'db_table': 'ward',
            },
        ),
        migrations.CreateModel(
            name='PollingUnit',
            fields=[
                ('uniqueid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('polling_unit_id', models.IntegerField()),
                ('ward_id', models.IntegerField()),
                ('polling_unit_number', models.CharField(max_length=50, null=True)),
                ('polling_unit_name', models.CharField(max_length=50, null=True)),
                ('polling_unit_description', models.TextField(null=True)),
                ('lat', models.CharField(max_length=255, null=True)),
                ('long', models.CharField(max_length=255, null=True)),
                ('entered_by_user', models.CharField(max_length=50)),
                ('date_entered', models.DateTimeField(null=True)),
                ('user_ip_address', models.CharField(max_length=50)),
                ('lga_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polling_units', to='election.lga', to_field='lga_id')),
                ('uniquewardid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polling_units', to='election.ward')),
            ],
            options={
                'db_table': 'polling_unit',
            },
        ),
        migrations.AddField(
            model_name='lga',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LGAs', to='election.states'),
        ),
        migrations.CreateModel(
            name='AnnouncedWardResults',
            fields=[
                ('result_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('party_abbreviation', models.CharField(max_length=4)),
                ('party_score', models.IntegerField()),
                ('entered_by_user', models.CharField(max_length=50)),
                ('date_entered', models.DateTimeField()),
                ('user_ip_address', models.CharField(max_length=50)),
                ('ward_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='election.ward', to_field='ward_name')),
            ],
            options={
                'db_table': 'announced_ward_results',
            },
        ),
        migrations.CreateModel(
            name='AnnouncedPuResults',
            fields=[
                ('result_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('party_abbreviation', models.CharField(max_length=4)),
                ('party_score', models.IntegerField()),
                ('entered_by_user', models.CharField(max_length=50)),
                ('date_entered', models.DateTimeField()),
                ('user_ip_address', models.CharField(max_length=50)),
                ('polling_unit_uniqueid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='election.pollingunit')),
            ],
            options={
                'db_table': 'announced_pu_results',
            },
        ),
        migrations.CreateModel(
            name='AnnouncedLgaResults',
            fields=[
                ('result_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('party_abbreviation', models.CharField(max_length=4)),
                ('party_score', models.IntegerField()),
                ('entered_by_user', models.CharField(max_length=50)),
                ('date_entered', models.DateTimeField()),
                ('user_ip_address', models.CharField(max_length=50)),
                ('lga_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='election.lga', to_field='lga_id')),
            ],
            options={
                'db_table': 'announced_lga_results',
            },
        ),
        migrations.CreateModel(
            name='AgentName',
            fields=[
                ('name_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=13)),
                ('pollingunit_uniqueid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='election.pollingunit')),
            ],
            options={
                'db_table': 'agentname',
            },
        ),
    ]
