# Generated by Django 4.2.10 on 2024-02-12 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentname',
            old_name='pollingunit_uniqueid',
            new_name='pollingunit_unique_id',
        ),
        migrations.RenameField(
            model_name='announcedlgaresults',
            old_name='lga_id',
            new_name='lga',
        ),
        migrations.RenameField(
            model_name='lga',
            old_name='state_id',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='pollingunit',
            old_name='lga_id',
            new_name='lga',
        ),
        migrations.RenameField(
            model_name='ward',
            old_name='lga_id',
            new_name='lga',
        ),
    ]
