# Generated by Django 4.2.10 on 2024-02-12 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_rename_pollingunit_uniqueid_agentname_pollingunit_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollingunit',
            name='entered_by_user',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
