# Generated by Django 4.2.10 on 2024-02-12 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0004_alter_pollingunit_user_ip_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentname',
            old_name='pollingunit_unique_id',
            new_name='pollingunit_unique',
        ),
    ]
